interval-in-seconds: 300
first-retry-after-error-in-seconds: 60
source-directory: example
file-determination-by-date: false
retention-period-in-hours: 336
http:
  url: <url>
  method: POST
  expected-status: 201
