interval-in-seconds: 300
first-retry-after-error-in-seconds: 60
source-directory: data
file-determination-by-date: false
retention-period-in-hours: 336
# http:
#   url: <url>
#   method: PUT
#   expected-status: 204
#   basic-auth-username: <username>
#   basic-auth-password: <password>
ntfy:
  url: <url>
  topic: <topic>
  title-template: "%s Temperature and humidity"
  message-template: "%.1f°C  %.1f%%"
  tags:
   - thermometer
   - droplet