FROM golang:1.21 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main ./cmd/main.go

FROM gcr.io/distroless/static-debian12 as runner
WORKDIR /app
COPY --from=builder /app/main ./main
USER nonroot:nonroot
ENTRYPOINT ["/app/main"]
