FROM arm32v7/golang:1.21 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build -o main ./cmd/main.go

FROM arm32v7/debian:12.1-slim as runner
WORKDIR /app
COPY --from=builder /app/main ./main
RUN groupadd -g 999 nonroot && \
    useradd -r -u 999 -g nonroot nonroot
USER nonroot
ENTRYPOINT ["/app/main"]
